package com.example.blinknotes.domain.model

data class User(
    val userId: String = "",
    val username: String = "",
    val email: String = "",
    val profileImage: String = "",
    val followers: List<String> = emptyList(),
    val following: List<String> = emptyList(),
    val createdAt: Long = System.currentTimeMillis(),
    val blinkNotesId: String = "",
    val bio: String = "",
    val coverImage: String = "",
    val followersCount: Int = 0,
    val followingCount: Int = 0,
    val recentPost: List<RecentPost> = emptyList(),
    val hasStory: Boolean = false,
    val hasMoment: Boolean = false,
    val isOnline: Boolean = false,
    val isStoryActive: Boolean = false,
    val isMoment: Boolean = false,
    val isMomentSeen: Boolean = false,
    val isStorySeen: Boolean = false,
    val isFriend: Boolean = false,
    val note: String = "",
    val latestMessage: String = "",
    val unreadMessages: Int = 0,
    val fcmToken: String? = null,
    val facebookLink: String? = null,
    val instagramLink: String? = null,
    val twitterLink: String? = null,
    val blockedUsers : List<String> = emptyList(),
    val isAdmin: Boolean = false,
    val isBlocked : Boolean = false,
)